plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/priyanshsoni/Desktop/ai-readiness-tool"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/ai-business-fluency"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]